# This workflow will do a clean install of node dependencies, run npm lint, build the source code and run tests.
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: NPM install
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Build library
      run: npm run build --if-present

    - name: Unit tests
      run: npm test
